---
title: "Data Cleansing Project"
author: "Radosław Bysewski"
date: "3 09 2021"
output: 
  github_document:
    fig_width: 17
    fig_height: 10
---

```{r setup, include=FALSE}
set.seed(2510)
knitr::opts_chunk$set(echo = TRUE,
                      fig.align="center",
                      fig.path = "grpahics/")
```

```{r Load libraries, message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)  

```

```{r Data Import}
input_dir <- sprintf("%s/input", getwd())
input_dir

for(file in list.files(input_dir)){
  name <- substring(file, 1, 1)
  df   <- readxl::read_excel(sprintf("%s/%s", input_dir, file))
  assign(name, df)
  rm(file, name, df)
}
```

```{r Data Wrangle}
main <- dplyr::left_join(g, t, by = c("x1" = "Team_ID")) %>% 
  dplyr::left_join(t, by = c("x2" = "Team_ID")) %>% 
  dplyr::select(Game_ID, Date, x2, x2, x1_N = Team_Short.x , x2_N = Team_Short.y) %>%
  dplyr::left_join(o, by = "Game_ID") %>% 
  dplyr::left_join(l, by = "Game_ID") %>%                         
  dplyr::left_join(p, by = "Game_ID") %>%                         
  dplyr::left_join(b, by = "Game_ID") %>%                         
  dplyr::left_join(s, by = "Game_ID")                         
```
